# Generated by Django 3.2.25 on 2024-06-02 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0002_auto_20240513_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.collaborator')),
            ],
        ),
    ]
