# Generated by Django 3.2.25 on 2024-06-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0004_rename_data_collaboratordate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratordate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
